# Generated by Django 4.2.25 on 2026-07-01 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eclinic', '0008_globalmedication_clinicinventory_global_medication_and_more'),
        ('patients', '0003_patientaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic where this patient was registered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to='eclinic.clinic'),
        ),
    ]
