# Generated by Django 4.2.25 on 2026-07-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patientclinicregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='clinic',
        ),
        migrations.DeleteModel(
            name='PatientClinicRegistration',
        ),
    ]
