# Generated by Django 4.2.25 on 2026-07-01 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eclinic', '0008_globalmedication_clinicinventory_global_medication_and_more'),
        ('patients', '0006_remove_patientprofile_clinic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic where this patient was registered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to='eclinic.clinic'),
        ),
        migrations.CreateModel(
            name='PatientClinicRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('registration_source', models.CharField(choices=[('admin_created', 'Admin Created'), ('self_registered', 'Self Registered'), ('consultation', 'Consultation'), ('other', 'Other')], default='other', max_length=50)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_registrations', to='eclinic.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_clinic_registrations',
                'unique_together': {('patient', 'clinic')},
            },
        ),
    ]
